cafe-papi:
  host: "cafe-p-api-t02cdx.5sc6y6-3.usa-e2.cloudhub.io"
  port: "80"
  createRecordPath: "api/customer/createRecord"
  updateRecordPath: "api/customer/updateRecord"
  getRecordPath: "api/customer/getRecord"